[build-system]
requires = [
    "cython>=0.27.3",
    "oldest-supported-numpy; python_version!='3.8'",
    "numpy>=1.19.3; python_version=='3.8'",
    "setuptools>=43.0.0",
    "wheel",
]
build-backend = "setuptools.build_meta"
